/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_me_patch"];
        trace?: never;
    };
    "/api/trees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trees */
        get: operations["list_trees_api_trees_get"];
        put?: never;
        /** Create Tree */
        post: operations["create_tree_api_trees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tree */
        get: operations["get_tree_api_trees__tree_id__get"];
        put?: never;
        post?: never;
        /** Delete Tree */
        delete: operations["delete_tree_api_trees__tree_id__delete"];
        options?: never;
        head?: never;
        /** Update Tree */
        patch: operations["update_tree_api_trees__tree_id__patch"];
        trace?: never;
    };
    "/api/trees/{tree_id}/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer Ownership */
        post: operations["transfer_ownership_api_trees__tree_id__transfer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_trees__tree_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_trees__tree_id__members__member_id__delete"];
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_api_trees__tree_id__members__member_id__patch"];
        trace?: never;
    };
    "/api/trees/{tree_id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invites */
        get: operations["list_invites_api_trees__tree_id__invites_get"];
        put?: never;
        /** Create Invite */
        post: operations["create_invite_api_trees__tree_id__invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invite */
        delete: operations["revoke_invite_api_trees__tree_id__invites__invite_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Invite */
        get: operations["preview_invite_api_invites__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invite */
        post: operations["accept_invite_api_invites__token__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/subtrees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subtrees */
        get: operations["list_subtrees_api_trees__tree_id__subtrees_get"];
        put?: never;
        /** Create Subtree */
        post: operations["create_subtree_api_trees__tree_id__subtrees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/subtrees/{subtree_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Subtree */
        delete: operations["delete_subtree_api_trees__tree_id__subtrees__subtree_id__delete"];
        options?: never;
        head?: never;
        /** Update Subtree */
        patch: operations["update_subtree_api_trees__tree_id__subtrees__subtree_id__patch"];
        trace?: never;
    };
    "/api/trees/{tree_id}/subtrees/{subtree_id}/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subtree People */
        get: operations["subtree_people_api_trees__tree_id__subtrees__subtree_id__people_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List People */
        get: operations["list_people_api_trees__tree_id__people_get"];
        put?: never;
        /** Create Person */
        post: operations["create_person_api_trees__tree_id__people_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/people/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["get_person_api_trees__tree_id__people__person_id__get"];
        put?: never;
        post?: never;
        /** Delete Person */
        delete: operations["delete_person_api_trees__tree_id__people__person_id__delete"];
        options?: never;
        head?: never;
        /** Update Person */
        patch: operations["update_person_api_trees__tree_id__people__person_id__patch"];
        trace?: never;
    };
    "/api/trees/{tree_id}/people/{person_id}/relatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect Relative
         * @description Connect this person, already on the tree, to `body.person_id`.
         *
         *     It works exactly like adding someone new with `relative`: {"person_id": X, "relation":
         *     "child"} records them as X's child. That also covers turning a step-parent into a parent.
         */
        post: operations["connect_relative_api_trees__tree_id__people__person_id__relatives_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/people/{person_id}/relatives/{relative_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect Relative
         * @description Remove a direct link: a parent, a child, a partner with no children together, or a
         *     sibling recorded without parents. Nobody is deleted.
         */
        delete: operations["disconnect_relative_api_trees__tree_id__people__person_id__relatives__relative_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/people/{person_id}/linked-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Link User
         * @description Admins connect (or disconnect) a member's account to the person they are.
         */
        put: operations["link_user_api_trees__tree_id__people__person_id__linked_user_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/people/{person_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Person Event */
        post: operations["add_person_event_api_trees__tree_id__people__person_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/families/{family_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Family Event */
        post: operations["add_family_event_api_trees__tree_id__families__family_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Event */
        delete: operations["delete_event_api_trees__tree_id__events__event_id__delete"];
        options?: never;
        head?: never;
        /** Update Event */
        patch: operations["update_event_api_trees__tree_id__events__event_id__patch"];
        trace?: never;
    };
    "/api/trees/{tree_id}/families/{family_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Family */
        patch: operations["update_family_api_trees__tree_id__families__family_id__patch"];
        trace?: never;
    };
    "/api/trees/{tree_id}/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Places */
        get: operations["list_places_api_trees__tree_id__places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tree Graph */
        get: operations["tree_graph_api_trees__tree_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/people/{person_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Photos */
        get: operations["list_photos_api_trees__tree_id__people__person_id__photos_get"];
        put?: never;
        /**
         * Upload Photo
         * @description Add a photo to someone's gallery. Their first becomes their profile picture.
         */
        post: operations["upload_photo_api_trees__tree_id__people__person_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/people/{person_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Profile Photo */
        put: operations["set_profile_photo_api_trees__tree_id__people__person_id__photo_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Photo */
        delete: operations["delete_photo_api_trees__tree_id__photos__photo_id__delete"];
        options?: never;
        head?: never;
        /** Update Photo */
        patch: operations["update_photo_api_trees__tree_id__photos__photo_id__patch"];
        trace?: never;
    };
    "/api/trees/{tree_id}/photos/{photo_id}/{size}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Photo File
         * @description The image, as WebP: `thumb` (up to 480px) or `full` (up to 2048px).
         */
        get: operations["photo_file_api_trees__tree_id__photos__photo_id___size__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Cover
         * @description Replace the tree's cover photo (admins).
         */
        put: operations["set_cover_api_trees__tree_id__cover_put"];
        post?: never;
        /** Remove Cover */
        delete: operations["remove_cover_api_trees__tree_id__cover_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/people/{person_id}/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conditions
         * @description Their recorded conditions, and what close blood relatives have recorded.
         */
        get: operations["list_conditions_api_trees__tree_id__people__person_id__conditions_get"];
        put?: never;
        /** Add Condition */
        post: operations["add_condition_api_trees__tree_id__people__person_id__conditions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{tree_id}/conditions/{condition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Condition */
        delete: operations["delete_condition_api_trees__tree_id__conditions__condition_id__delete"];
        options?: never;
        head?: never;
        /** Update Condition */
        patch: operations["update_condition_api_trees__tree_id__conditions__condition_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_set_cover_api_trees__tree_id__cover_put */
        Body_set_cover_api_trees__tree_id__cover_put: {
            /** File */
            file: string;
        };
        /** Body_upload_photo_api_trees__tree_id__people__person_id__photos_post */
        Body_upload_photo_api_trees__tree_id__people__person_id__photos_post: {
            /** File */
            file: string;
            /**
             * Caption
             * @default
             */
            caption?: string;
        };
        /**
         * ChildRelation
         * @enum {string}
         */
        ChildRelation: "biological" | "adopted" | "step" | "foster";
        /** ConditionIn */
        ConditionIn: {
            /** Name */
            name: string;
            status: components["schemas"]["ConditionStatus"];
            /** Year */
            year?: number | null;
            /**
             * Note
             * @default
             */
            note?: string;
        };
        /** ConditionOut */
        ConditionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Name */
            name: string;
            status: components["schemas"]["ConditionStatus"];
            /** Year */
            year: number | null;
            /** Note */
            note: string;
        };
        /**
         * ConditionStatus
         * @enum {string}
         */
        ConditionStatus: "diagnosed" | "carrier" | "watch" | "untested";
        /** ConditionUpdate */
        ConditionUpdate: {
            /** Name */
            name?: string | null;
            status?: components["schemas"]["ConditionStatus"] | null;
            /** Year */
            year?: number | null;
            /** Note */
            note?: string | null;
        };
        /** ConditionsOut */
        ConditionsOut: {
            /** Recorded */
            recorded: components["schemas"]["ConditionOut"][];
            /** Inherited */
            inherited: components["schemas"]["InheritedConditionOut"][];
        };
        /**
         * DateQualifier
         * @enum {string}
         */
        DateQualifier: "exact" | "about" | "before" | "after" | "between";
        /** EventIn */
        EventIn: {
            type: components["schemas"]["EventType"];
            /**
             * Title
             * @default
             */
            title?: string;
            /**
             * Description
             * @default
             */
            description?: string;
            date?: components["schemas"]["FuzzyDate"] | null;
            /** Place */
            place?: string | null;
        };
        /** EventOut */
        EventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Person Id */
            person_id: string | null;
            /** Family Id */
            family_id: string | null;
            type: components["schemas"]["EventType"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            date: components["schemas"]["FuzzyDateOut"] | null;
            /** Place */
            place: string | null;
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "birth" | "baptism" | "death" | "burial" | "education" | "occupation" | "retirement" | "residence" | "emigration" | "immigration" | "military" | "engagement" | "marriage" | "separation" | "divorce" | "other";
        /** EventUpdate */
        EventUpdate: {
            type?: components["schemas"]["EventType"] | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            date?: components["schemas"]["FuzzyDate"] | null;
            /** Place */
            place?: string | null;
        };
        /** FamilyOut */
        FamilyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["PartnerStatus"];
            /** Partner Ids */
            partner_ids: string[];
            /** Child Ids */
            child_ids: string[];
        };
        /** FamilyUpdate */
        FamilyUpdate: {
            status: components["schemas"]["PartnerStatus"];
        };
        /** Favorite */
        Favorite: {
            /** Category */
            category: string;
            /** Value */
            value: string;
        };
        /** FuzzyDate */
        FuzzyDate: {
            /** @default exact */
            qualifier?: components["schemas"]["DateQualifier"];
            /** Year */
            year?: number | null;
            /** Month */
            month?: number | null;
            /** Day */
            day?: number | null;
            /** Year2 */
            year2?: number | null;
            /** Month2 */
            month2?: number | null;
            /** Day2 */
            day2?: number | null;
            /**
             * Phrase
             * @default
             */
            phrase?: string;
        };
        /** FuzzyDateOut */
        FuzzyDateOut: {
            /** @default exact */
            qualifier: components["schemas"]["DateQualifier"];
            /** Year */
            year: number | null;
            /** Month */
            month: number | null;
            /** Day */
            day: number | null;
            /** Year2 */
            year2: number | null;
            /** Month2 */
            month2: number | null;
            /** Day2 */
            day2: number | null;
            /**
             * Phrase
             * @default
             */
            phrase: string;
            /** Label */
            readonly label: string;
            /** Short */
            readonly short: string;
        };
        /** GraphChild */
        GraphChild: {
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            relation: components["schemas"]["ChildRelation"];
        };
        /**
         * GraphFamily
         * @description A couple (or single parent) and their children, as drawn on the canvas.
         */
        GraphFamily: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["PartnerStatus"];
            /** Partner Ids */
            partner_ids: string[];
            /** Children */
            children: components["schemas"]["GraphChild"][];
            /**
             * Married
             * @default false
             */
            married: boolean;
            marriage: components["schemas"]["FuzzyDateOut"] | null;
        };
        /**
         * GraphPerson
         * @description What the tree canvas needs to draw one person.
         */
        GraphPerson: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Given Names */
            given_names: string;
            /** Surname */
            surname: string;
            sex: components["schemas"]["Sex"];
            /** Is Living */
            is_living: boolean;
            /** Photo Id */
            photo_id: string | null;
            /** Linked User Id */
            linked_user_id: string | null;
            birth: components["schemas"]["VitalOut"] | null;
            death: components["schemas"]["VitalOut"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InheritedConditionOut
         * @description Something a close blood relative has recorded: worth keeping an eye on.
         */
        InheritedConditionOut: {
            /** Name */
            name: string;
            status: components["schemas"]["ConditionStatus"];
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Via */
            via: string[];
            /** Generations */
            generations: number;
            /** Others */
            others: number;
        };
        /** InviteAccepted */
        InviteAccepted: {
            /**
             * Tree Id
             * Format: uuid
             */
            tree_id: string;
        };
        /** InviteCreate */
        InviteCreate: {
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "contributor" | "personal";
            /** Subtree Id */
            subtree_id?: string | null;
            /** Email */
            email?: string | null;
            /** Person Id */
            person_id?: string | null;
        };
        /** InviteOut */
        InviteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Token */
            token: string;
            role: components["schemas"]["Role"];
            /** Subtree Id */
            subtree_id: string | null;
            /** Email */
            email: string | null;
            /** Person Id */
            person_id: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Accepted At */
            accepted_at: string | null;
            /** Revoked */
            revoked: boolean;
        };
        /** InvitePreview */
        InvitePreview: {
            /** Tree Name */
            tree_name: string;
            /** Subtree Name */
            subtree_name: string | null;
            role: components["schemas"]["Role"];
            /** Person Name */
            person_name: string | null;
            /** Usable */
            usable: boolean;
        };
        /** LinkUser */
        LinkUser: {
            /** User Id */
            user_id: string | null;
        };
        /** MemberOut */
        MemberOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            user: components["schemas"]["UserOut"];
            role: components["schemas"]["Role"];
            /** Subtree Id */
            subtree_id: string | null;
            /** Subtree Name */
            subtree_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MemberUpdate */
        MemberUpdate: {
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "contributor" | "personal";
        };
        /** MyAccessOut */
        MyAccessOut: {
            tree_role: components["schemas"]["Role"] | null;
            /** Subtree Roles */
            subtree_roles: components["schemas"]["SubtreeRoleOut"][];
            highest_role: components["schemas"]["Role"];
            /** My Person Id */
            my_person_id: string | null;
            /** Can Manage Members */
            can_manage_members: boolean;
            /** Can Manage Subtrees */
            can_manage_subtrees: boolean;
            /** Can Create People */
            can_create_people: boolean;
            /** Is Owner */
            is_owner: boolean;
        };
        /**
         * PartnerStatus
         * @enum {string}
         */
        PartnerStatus: "together" | "separated" | "divorced";
        /** PersonCreate */
        PersonCreate: {
            /**
             * Given Names
             * @default
             */
            given_names?: string;
            /**
             * Surname
             * @default
             */
            surname?: string;
            /**
             * Birth Surname
             * @default
             */
            birth_surname?: string;
            /**
             * Nickname
             * @default
             */
            nickname?: string;
            /**
             * Native Name
             * @default
             */
            native_name?: string;
            /** @default unknown */
            sex?: components["schemas"]["Sex"];
            /**
             * Bio
             * @default
             */
            bio?: string;
            /**
             * Occupation
             * @default
             */
            occupation?: string;
            /**
             * Nationality
             * @default
             */
            nationality?: string;
            /**
             * Education
             * @default
             */
            education?: string;
            /** Links */
            links?: components["schemas"]["SocialLink-Input"][];
            /** Vehicles */
            vehicles?: string[];
            /** Pets */
            pets?: components["schemas"]["Pet-Input"][];
            /** Favorites */
            favorites?: components["schemas"]["Favorite"][];
            /**
             * Is Living
             * @default true
             */
            is_living?: boolean;
            /**
             * Is Me
             * @default false
             */
            is_me?: boolean;
            relative?: components["schemas"]["RelativeLink"] | null;
            birth?: components["schemas"]["FuzzyDate"] | null;
            death?: components["schemas"]["FuzzyDate"] | null;
        };
        /** PersonDetailOut */
        PersonDetailOut: {
            /**
             * Given Names
             * @default
             */
            given_names: string;
            /**
             * Surname
             * @default
             */
            surname: string;
            /**
             * Birth Surname
             * @default
             */
            birth_surname: string;
            /**
             * Nickname
             * @default
             */
            nickname: string;
            /**
             * Native Name
             * @default
             */
            native_name: string;
            /** @default unknown */
            sex: components["schemas"]["Sex"];
            /**
             * Bio
             * @default
             */
            bio: string;
            /**
             * Occupation
             * @default
             */
            occupation: string;
            /**
             * Nationality
             * @default
             */
            nationality: string;
            /**
             * Education
             * @default
             */
            education: string;
            /** Links */
            links: components["schemas"]["SocialLink-Output"][];
            /** Vehicles */
            vehicles: string[];
            /** Pets */
            pets: components["schemas"]["Pet-Output"][];
            /** Favorites */
            favorites: components["schemas"]["Favorite"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tree Id
             * Format: uuid
             */
            tree_id: string;
            /** Is Living */
            is_living: boolean;
            /** Display Name */
            display_name: string;
            /** Linked User Id */
            linked_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Photo Id */
            photo_id: string | null;
            birth: components["schemas"]["VitalOut"] | null;
            death: components["schemas"]["VitalOut"] | null;
            permissions: components["schemas"]["PersonPermissions"];
            /** Parents */
            parents: string[];
            /** Children */
            children: string[];
            /** Partners */
            partners: string[];
            /** Only Parent Of */
            only_parent_of: string[];
            /** Relatives */
            relatives: components["schemas"]["RelativeOut"][];
            /** Timeline */
            timeline: components["schemas"]["TimelineItem"][];
        };
        /** PersonOut */
        PersonOut: {
            /**
             * Given Names
             * @default
             */
            given_names: string;
            /**
             * Surname
             * @default
             */
            surname: string;
            /**
             * Birth Surname
             * @default
             */
            birth_surname: string;
            /**
             * Nickname
             * @default
             */
            nickname: string;
            /**
             * Native Name
             * @default
             */
            native_name: string;
            /** @default unknown */
            sex: components["schemas"]["Sex"];
            /**
             * Bio
             * @default
             */
            bio: string;
            /**
             * Occupation
             * @default
             */
            occupation: string;
            /**
             * Nationality
             * @default
             */
            nationality: string;
            /**
             * Education
             * @default
             */
            education: string;
            /** Links */
            links: components["schemas"]["SocialLink-Output"][];
            /** Vehicles */
            vehicles: string[];
            /** Pets */
            pets: components["schemas"]["Pet-Output"][];
            /** Favorites */
            favorites: components["schemas"]["Favorite"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tree Id
             * Format: uuid
             */
            tree_id: string;
            /** Is Living */
            is_living: boolean;
            /** Display Name */
            display_name: string;
            /** Linked User Id */
            linked_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Photo Id */
            photo_id: string | null;
            birth: components["schemas"]["VitalOut"] | null;
            death: components["schemas"]["VitalOut"] | null;
        };
        /** PersonPermissions */
        PersonPermissions: {
            /** Can Edit */
            can_edit: boolean;
            /** Can Set Living */
            can_set_living: boolean;
            /** Can Delete */
            can_delete: boolean;
            /** Can Add Relatives */
            can_add_relatives: boolean;
            /** Can View Conditions */
            can_view_conditions: boolean;
            /** Can Edit Conditions */
            can_edit_conditions: boolean;
        };
        /** PersonUpdate */
        PersonUpdate: {
            /** Given Names */
            given_names?: string | null;
            /** Surname */
            surname?: string | null;
            /** Birth Surname */
            birth_surname?: string | null;
            /** Nickname */
            nickname?: string | null;
            /** Native Name */
            native_name?: string | null;
            sex?: components["schemas"]["Sex"] | null;
            /** Bio */
            bio?: string | null;
            /** Is Living */
            is_living?: boolean | null;
            /** Occupation */
            occupation?: string | null;
            /** Nationality */
            nationality?: string | null;
            /** Education */
            education?: string | null;
            /** Links */
            links?: components["schemas"]["SocialLink-Input"][] | null;
            /** Vehicles */
            vehicles?: string[] | null;
            /** Pets */
            pets?: components["schemas"]["Pet-Input"][] | null;
            /** Favorites */
            favorites?: components["schemas"]["Favorite"][] | null;
        };
        /** Pet */
        "Pet-Input": {
            /** Name */
            name: string;
            /**
             * Kind
             * @default
             */
            kind?: string;
        };
        /** Pet */
        "Pet-Output": {
            /** Name */
            name: string;
            /**
             * Kind
             * @default
             */
            kind: string;
        };
        /**
         * PhotoOut
         * @description A photo. The image is at /api/trees/{tree_id}/photos/{id}/thumb or /full.
         */
        PhotoOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tree Id
             * Format: uuid
             */
            tree_id: string;
            /** Person Id */
            person_id: string | null;
            /** Caption */
            caption: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PhotoUpdate */
        PhotoUpdate: {
            /** Caption */
            caption: string;
        };
        /** PlaceOut */
        PlaceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * Preferences
         * @description App settings, saved to the account so they follow the user between devices.
         */
        Preferences: {
            /**
             * Theme
             * @default system
             * @enum {string}
             */
            theme: "system" | "light" | "dark";
            /**
             * Text Size
             * @default normal
             * @enum {string}
             */
            text_size: "normal" | "large";
            /**
             * Start Page
             * @default home
             * @enum {string}
             */
            start_page: "home" | "tree";
        };
        /**
         * PreferencesUpdate
         * @description Only the settings given change.
         */
        PreferencesUpdate: {
            /** Theme */
            theme?: ("system" | "light" | "dark") | null;
            /** Text Size */
            text_size?: ("normal" | "large") | null;
            /** Start Page */
            start_page?: ("home" | "tree") | null;
        };
        /** ProfilePhoto */
        ProfilePhoto: {
            /** Photo Id */
            photo_id: string | null;
        };
        /**
         * RelativeLink
         * @description How a person, new or already on the tree, is connected to `person_id`.
         */
        RelativeLink: {
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "parent" | "child" | "partner" | "sibling" | "step_parent" | "step_child" | "step_sibling";
            /** Family Id */
            family_id?: string | null;
            /**
             * New Family
             * @default false
             */
            new_family?: boolean;
            /** Via Person Id */
            via_person_id?: string | null;
            /** @default together */
            status?: components["schemas"]["PartnerStatus"];
            /**
             * Also Parent Of
             * @default []
             */
            also_parent_of?: string[];
        };
        /** RelativeOut */
        RelativeOut: {
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "parent" | "step_parent" | "partner" | "sibling" | "half_sibling" | "step_sibling" | "child" | "step_child";
            pedigree: components["schemas"]["ChildRelation"] | null;
            /** Family Id */
            family_id: string | null;
            status: components["schemas"]["PartnerStatus"] | null;
            /** Via Person Id */
            via_person_id: string | null;
            /**
             * Can Edit Family
             * @default false
             */
            can_edit_family: boolean;
            /**
             * Can Make Parent
             * @default false
             */
            can_make_parent: boolean;
            /**
             * Can Unlink
             * @default false
             */
            can_unlink: boolean;
        };
        /**
         * Role
         * @description Membership roles, lowest to highest privilege.
         * @enum {string}
         */
        Role: "personal" | "contributor" | "admin" | "owner";
        /**
         * Sex
         * @enum {string}
         */
        Sex: "male" | "female" | "other" | "unknown";
        /** SocialLink */
        "SocialLink-Input": {
            /** Url */
            url: string;
            /**
             * Label
             * @default
             */
            label?: string;
        };
        /** SocialLink */
        "SocialLink-Output": {
            /** Url */
            url: string;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** SubtreeCreate */
        SubtreeCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description?: string;
            /**
             * Root Person Id
             * Format: uuid
             */
            root_person_id: string;
            /** @default descendants */
            direction?: components["schemas"]["SubtreeDirection"];
            /**
             * Include Spouses
             * @default true
             */
            include_spouses?: boolean;
        };
        /**
         * SubtreeDirection
         * @enum {string}
         */
        SubtreeDirection: "descendants" | "ancestors" | "both";
        /** SubtreeOut */
        SubtreeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Root Person Id
             * Format: uuid
             */
            root_person_id: string;
            direction: components["schemas"]["SubtreeDirection"];
            /** Include Spouses */
            include_spouses: boolean;
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
        };
        /** SubtreeRoleOut */
        SubtreeRoleOut: {
            /**
             * Subtree Id
             * Format: uuid
             */
            subtree_id: string;
            /** Subtree Name */
            subtree_name: string;
            role: components["schemas"]["Role"];
        };
        /** SubtreeUpdate */
        SubtreeUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Root Person Id */
            root_person_id?: string | null;
            direction?: components["schemas"]["SubtreeDirection"] | null;
            /** Include Spouses */
            include_spouses?: boolean | null;
        };
        /** TimelineItem */
        TimelineItem: {
            /** Key */
            key: string;
            /** Event Id */
            event_id: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "person" | "family" | "child_birth" | "partner_death";
            type: components["schemas"]["EventType"];
            /** Type Label */
            type_label: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            date: components["schemas"]["FuzzyDateOut"] | null;
            /** Place */
            place: string | null;
            /** Family Id */
            family_id: string | null;
            /** Related Person Id */
            related_person_id: string | null;
            /** Editable */
            editable: boolean;
        };
        /** TransferOwnership */
        TransferOwnership: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** TreeCreate */
        TreeCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description?: string;
        };
        /** TreeDetailOut */
        TreeDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cover Photo Id */
            cover_photo_id: string | null;
            access: components["schemas"]["MyAccessOut"];
            /** Person Count */
            person_count: number;
            /** Photo Count */
            photo_count: number;
        };
        /** TreeGraphOut */
        TreeGraphOut: {
            /** People */
            people: components["schemas"]["GraphPerson"][];
            /** Families */
            families: components["schemas"]["GraphFamily"][];
        };
        /** TreeListItem */
        TreeListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cover Photo Id */
            cover_photo_id: string | null;
            highest_role: components["schemas"]["Role"];
        };
        /** TreeOut */
        TreeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cover Photo Id */
            cover_photo_id: string | null;
        };
        /** TreeUpdate */
        TreeUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url: string | null;
            preferences: components["schemas"]["Preferences"];
        };
        /** UserUpdate */
        UserUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            preferences?: components["schemas"]["PreferencesUpdate"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VitalOut
         * @description A birth or death: when and where.
         */
        VitalOut: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            date: components["schemas"]["FuzzyDateOut"] | null;
            /** Place */
            place: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_me_api_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trees_api_trees_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeListItem"][];
                };
            };
        };
    };
    create_tree_api_trees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TreeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tree_api_trees__tree_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tree_api_trees__tree_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tree_api_trees__tree_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TreeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfer_ownership_api_trees__tree_id__transfer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOwnership"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_trees__tree_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_trees__tree_id__members__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_trees__tree_id__members__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invites_api_trees__tree_id__invites_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_api_trees__tree_id__invites_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invite_api_trees__tree_id__invites__invite_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_invite_api_invites__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invite_api_invites__token__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subtrees_api_trees__tree_id__subtrees_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtreeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subtree_api_trees__tree_id__subtrees_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubtreeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtreeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subtree_api_trees__tree_id__subtrees__subtree_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                subtree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subtree_api_trees__tree_id__subtrees__subtree_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                subtree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubtreeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtreeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subtree_people_api_trees__tree_id__subtrees__subtree_id__people_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                subtree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_people_api_trees__tree_id__people_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_person_api_trees__tree_id__people_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_api_trees__tree_id__people__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_person_api_trees__tree_id__people__person_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_person_api_trees__tree_id__people__person_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_relative_api_trees__tree_id__people__person_id__relatives_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelativeLink"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_relative_api_trees__tree_id__people__person_id__relatives__relative_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
                relative_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_user_api_trees__tree_id__people__person_id__linked_user_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkUser"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_person_event_api_trees__tree_id__people__person_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_family_event_api_trees__tree_id__families__family_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                family_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_event_api_trees__tree_id__events__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_api_trees__tree_id__events__event_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_family_api_trees__tree_id__families__family_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                family_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_places_api_trees__tree_id__places_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tree_graph_api_trees__tree_id__graph_get: {
        parameters: {
            query?: {
                /** @description Only this branch */
                subtree_id?: string | null;
            };
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeGraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_photos_api_trees__tree_id__people__person_id__photos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_photo_api_trees__tree_id__people__person_id__photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_photo_api_trees__tree_id__people__person_id__photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_profile_photo_api_trees__tree_id__people__person_id__photo_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePhoto"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePhoto"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_photo_api_trees__tree_id__photos__photo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_photo_api_trees__tree_id__photos__photo_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    photo_file_api_trees__tree_id__photos__photo_id___size__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                photo_id: string;
                size: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_cover_api_trees__tree_id__cover_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_set_cover_api_trees__tree_id__cover_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_cover_api_trees__tree_id__cover_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conditions_api_trees__tree_id__people__person_id__conditions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_condition_api_trees__tree_id__people__person_id__conditions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConditionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_condition_api_trees__tree_id__conditions__condition_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                condition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_condition_api_trees__tree_id__conditions__condition_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tree_id: string;
                condition_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConditionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
