"""events, places, profile details, couple status

Revision ID: 5436c9281d06
Revises: ca974c7ad7fa
Create Date: 2026-09-25 17:22:02.954924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5436c9281d06'
down_revision: Union[str, Sequence[str], None] = 'ca974c7ad7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_places_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places')),
    sa.UniqueConstraint('tree_id', 'name', name='uq_place_name')
    )
    op.create_index(op.f('ix_places_tree_id'), 'places', ['tree_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('birth', 'baptism', 'death', 'burial', 'education', 'occupation', 'retirement', 'residence', 'emigration', 'immigration', 'military', 'engagement', 'marriage', 'separation', 'divorce', 'other', name='eventtype', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_qualifier', sa.Enum('exact', 'about', 'before', 'after', 'between', name='datequalifier', native_enum=False, length=20), nullable=True),
    sa.Column('date_year', sa.SmallInteger(), nullable=True),
    sa.Column('date_month', sa.SmallInteger(), nullable=True),
    sa.Column('date_day', sa.SmallInteger(), nullable=True),
    sa.Column('date_year2', sa.SmallInteger(), nullable=True),
    sa.Column('date_month2', sa.SmallInteger(), nullable=True),
    sa.Column('date_day2', sa.SmallInteger(), nullable=True),
    sa.Column('date_phrase', sa.String(length=200), nullable=False),
    sa.Column('sort_date', sa.Date(), nullable=True),
    sa.Column('place_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(person_id IS NULL) <> (family_id IS NULL)', name=op.f('ck_events_one_owner')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_events_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_events_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_events_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_events_place_id_places'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_events_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_family_id'), 'events', ['family_id'], unique=False)
    op.create_index(op.f('ix_events_person_id'), 'events', ['person_id'], unique=False)
    op.create_index(op.f('ix_events_sort_date'), 'events', ['sort_date'], unique=False)
    op.create_index(op.f('ix_events_tree_id'), 'events', ['tree_id'], unique=False)
    op.add_column('families', sa.Column('status', sa.Enum('together', 'separated', 'divorced', name='partnerstatus', native_enum=False, length=20), server_default='together', nullable=False))
    op.add_column('people', sa.Column('occupation', sa.String(length=200), server_default='', nullable=False))
    op.add_column('people', sa.Column('nationality', sa.String(length=200), server_default='', nullable=False))
    op.add_column('people', sa.Column('education', sa.String(length=300), server_default='', nullable=False))
    op.add_column('people', sa.Column('links', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('people', sa.Column('vehicles', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('people', sa.Column('pets', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('people', sa.Column('favorites', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'favorites')
    op.drop_column('people', 'pets')
    op.drop_column('people', 'vehicles')
    op.drop_column('people', 'links')
    op.drop_column('people', 'education')
    op.drop_column('people', 'nationality')
    op.drop_column('people', 'occupation')
    op.drop_column('families', 'status')
    op.drop_index(op.f('ix_events_tree_id'), table_name='events')
    op.drop_index(op.f('ix_events_sort_date'), table_name='events')
    op.drop_index(op.f('ix_events_person_id'), table_name='events')
    op.drop_index(op.f('ix_events_family_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_places_tree_id'), table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
