"""accounts, trees, memberships, invites, subtrees, people

Revision ID: ca974c7ad7fa
Revises: 
Create Date: 2026-09-25 13:22:59.249587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca974c7ad7fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auth_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_auth_id'), 'users', ['auth_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('trees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_trees_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trees'))
    )
    op.create_table('families',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_families_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_families'))
    )
    op.create_index(op.f('ix_families_tree_id'), 'families', ['tree_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('given_names', sa.String(length=200), nullable=False),
    sa.Column('surname', sa.String(length=200), nullable=False),
    sa.Column('birth_surname', sa.String(length=200), nullable=False),
    sa.Column('nickname', sa.String(length=200), nullable=False),
    sa.Column('native_name', sa.String(length=400), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', 'other', 'unknown', name='sex', native_enum=False, length=20), nullable=False),
    sa.Column('is_living', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('linked_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_people_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], name=op.f('fk_people_linked_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_people_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
    sa.UniqueConstraint('tree_id', 'linked_user_id', name='uq_person_linked_user')
    )
    op.create_index(op.f('ix_people_surname'), 'people', ['surname'], unique=False)
    op.create_index(op.f('ix_people_tree_id'), 'people', ['tree_id'], unique=False)
    op.create_table('child_links',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.Enum('biological', 'adopted', 'step', 'foster', name='childrelation', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_child_links_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_child_links_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('family_id', 'person_id', name=op.f('pk_child_links'))
    )
    op.create_index(op.f('ix_child_links_person_id'), 'child_links', ['person_id'], unique=False)
    op.create_table('family_partners',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_family_partners_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_family_partners_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('family_id', 'person_id', name=op.f('pk_family_partners'))
    )
    op.create_index(op.f('ix_family_partners_person_id'), 'family_partners', ['person_id'], unique=False)
    op.create_table('subtrees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_person_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('descendants', 'ancestors', 'both', name='subtreedirection', native_enum=False, length=20), nullable=False),
    sa.Column('include_spouses', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['root_person_id'], ['people.id'], name=op.f('fk_subtrees_root_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_subtrees_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subtrees'))
    )
    op.create_index(op.f('ix_subtrees_tree_id'), 'subtrees', ['tree_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('subtree_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('personal', 'contributor', 'admin', 'owner', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_id', sa.Uuid(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['users.id'], name=op.f('fk_invites_accepted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_invites_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_invites_person_id_people'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subtree_id'], ['subtrees.id'], name=op.f('fk_invites_subtree_id_subtrees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_invites_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites'))
    )
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    op.create_index(op.f('ix_invites_tree_id'), 'invites', ['tree_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subtree_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('personal', 'contributor', 'admin', 'owner', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subtree_id'], ['subtrees.id'], name=op.f('fk_memberships_subtree_id_subtrees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_memberships_tree_id_trees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('tree_id', 'user_id', 'subtree_id', name='uq_membership')
    )
    op.create_index(op.f('ix_memberships_subtree_id'), 'memberships', ['subtree_id'], unique=False)
    op.create_index(op.f('ix_memberships_tree_id'), 'memberships', ['tree_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tree_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_subtree_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invites_tree_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_subtrees_tree_id'), table_name='subtrees')
    op.drop_table('subtrees')
    op.drop_index(op.f('ix_family_partners_person_id'), table_name='family_partners')
    op.drop_table('family_partners')
    op.drop_index(op.f('ix_child_links_person_id'), table_name='child_links')
    op.drop_table('child_links')
    op.drop_index(op.f('ix_people_tree_id'), table_name='people')
    op.drop_index(op.f('ix_people_surname'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_families_tree_id'), table_name='families')
    op.drop_table('families')
    op.drop_table('trees')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
